# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MosaicPhotoGalleryLayouts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MosaicPhotoGalleryLayouts
  
  # UI表現の際に利用するライブラリ
  pod 'AnimatedCollectionViewLayout'
  pod 'Blueprints'
  pod 'FanMenu'
  pod 'Parchment'
  pod 'Nantes'
  pod 'PTCardTabBar'
  pod 'TagListView', '~> 1.0'
  pod 'FontAwesome.swift'
end
